module.exports = {
  projects: [
    '<rootDir>/apps/xlayers',
    '<rootDir>/libs/angular-codegen',
    '<rootDir>/libs/css-codegen',
    '<rootDir>/libs/lit-element-codegen',
    '<rootDir>/libs/react-codegen',
    '<rootDir>/libs/stencil-codegen',
    '<rootDir>/libs/svg-codegen',
    '<rootDir>/libs/vue-codegen',
    '<rootDir>/libs/web-codegen',
    '<rootDir>/libs/web-component-codegen',
    '<rootDir>/libs/xaml-codegen',
    '<rootDir>/libs/sketch-lib',
    '<rootDir>/libs/sketch-ingestor',
    '<rootDir>/libs/sketchtypes',
    '<rootDir>/libs/test-helpers',
    '<rootDir>/libs/ingestor',
  ],
};
