export const environment = {
  production: false,
  hmr: true,
  version: '_BUILD_HASH_',
  baseUrl: 'http://localhost:4200',
  demoFiles: [
    {
      value: 51,
      disabled: false,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
    {
      value: 52,
      disabled: false,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
    {
      value: 53,
      disabled: false,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
    {
      value: 59,
      disabled: false,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
    {
      value: 69,
      disabled: false,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
  ],
};
