name: mainworkflow

on:
  push:
    branches: [ main ]

jobs:
    build:
      name: install, test and build
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, windows-latest]
          node: [13, 14]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Get origin main
          run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
        - name: Cache node modules
          uses: actions/cache@v1
          env:
            cache-name: cache-node-modules
          with:
            path: |
              ~/.npm
              node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Install environment
          run: npm install
        - name: Tests coverage
          run: npm run nx run-many -- --target=test --all --codeCoverage
        - name: Tests e2e
          run: npm run nx e2e
        - name: Build
          run: npm run nx affected:build --base=origin/main~1 --head=origin/main --parallel=true --with-deps=true --prod
        - name: Stamp
          run: npm run stamp

